


export const Images ={
   
   
   lessonPlan2: require('../Assets/Icons/plan.png'),
   lessonPlan3: require('../Assets/Icons/lessonPlan.png'),
   reviewteacher: require('../Assets/Icons/reviewteacher.png'),
   downloadCenter: require('../Assets/Icons/download.png'),
   classRoutine: require('../Assets/Icons/classRoutine.png'),
   attendanceReport: require('../Assets/Icons/attendanceReport.png'),
   Board: require('../Assets/Icons/board.png'),
   homeworkColor: require('../Assets/Icons/homeworkIcon.png'),
   feesPayment: require('../Assets/Icons/feesPayment.png'),
   dailyAssignment2: require('../Assets/Icons/dailyAsignment.png'),
   transportation: require('../Assets/Icons/transportation.png'),

   schoolCode1: require('../Assets/Images/schollcode1.png'),
   logoImage: require('../Assets/Images/logoImage.png'),
   pageBackgound: require('../Assets/Images/pageBackgound.png'),
   loginBackground: require('../Assets/Images/loginBackground.jpg'),
   esmsLogo: require('../Assets/Images/esmsLogo.png'),
   profileImage: require('../Assets/Images/profileImage.jpg'),
   homework3: require('../Assets/Images/homework3.png'),
   noticeBoard: require('../Assets/Images/noticeBoard.jpg'),
   dailyAssignment: require('../Assets/Images/assignment.jpg'),
   editAssignment: require('../Assets/Images/editAssignment.png'),
   lessonPlan: require('../Assets/Images/lessonPlan.png'),
   fatherImage: require('../Assets/Images/fatherImage.png'),
   motherImage: require('../Assets/Images/motherImage.jpg'),
   guardianImage: require('../Assets/Images/guardianImage.jpg'),
   payment: require('../Assets/Images/payment.jpg'),
   issuedBooks: require('../Assets/Images/issuedBooks.jpg'),
   examinations: require('../Assets/Images/examinations.jpg'),
   exams: require('../Assets/Images/exams.jpg'),
   examresult: require('../Assets/Images/examresult.jpg'),
   Attendance: require('../Assets/Images/attendance.jpg'),
   transportRoutes: require('../Assets/Images/transportRoutes.png'),

   classtimetable: require('../Assets/Icons/classtimetable.png'),
   barcode: require('../Assets/Icons/barcode.png'),
   phoneCall: require('../Assets/Icons/phone-call.png'),
   profession: require('../Assets/Icons/profession.png'),
   relation: require('../Assets/Icons/relation.png'),
   address: require('../Assets/Icons/address.png'),
   email: require('../Assets/Icons/email.png'),
   rating: require('../Assets/Icons/star.png'),
   ratingBlank: require('../Assets/Icons/starBlank.png'),
   books: require('../Assets/Icons/books.png'),
   car: require('../Assets/Icons/car.png'),
   car2: require('../Assets/Icons/car2.png'),
   carStudent: require('../Assets/Icons/carStudent.png'),
   mystudents: require('../Assets/Icons/mystudents.png'),
   stopage: require('../Assets/Icons/stopage.png'),
   source: require('../Assets/Icons/source.png'),
   source2: require('../Assets/Icons/source2.svg'),
   destination: require('../Assets/Icons/destination.png'),

   home: require('../Assets/Icons/home.png'),
   profile: require('../Assets/Icons/profile.png'),
   logout: require('../Assets/Icons/logout.png'),

   padlock: require('../Assets/Icons/padlock.png'),
   username: require('../Assets/Icons/username.png'),
   eye: require('../Assets/Icons/eye.png'),
   hidden: require('../Assets/Icons/hidden.png'),
   rightArrow: require('../Assets/Icons/right-arrow.png'),
   notificationBell: require('../Assets/Icons/notification-bell.png'),
   menu: require('../Assets/Icons/menu.png'),
   // assignment: require('../Assets/Icons/assignment.png'),
   downloads: require('../Assets/Icons/downloads.png'),
   gmeet: require('../Assets/Icons/gmeet.png'),
   zoom: require('../Assets/Icons/zoom.png'),
   homework: require('../Assets/Icons/homework.png'),
   lession: require('../Assets/Icons/lession.png'),
   onlineCourse: require('../Assets/Icons/online-course.png'),
   onlineTest: require('../Assets/Icons/online-test.png'),
   timetable: require('../Assets/Icons/timetable.png'),
   syllabus: require('../Assets/Icons/syllabus.png'),
   attendance: require('../Assets/Icons/attendance.png'),
   examination: require('../Assets/Icons/test.png'),
   exam: require('../Assets/Icons/exam.png'),
   dailyAssignment: require('../Assets/Icons/dailyAssignment.png'),
   timeline: require('../Assets/Icons/timeline.png'),
   documents: require('../Assets/Icons/documents.png'),
   behaviour: require('../Assets/Icons/psychology.png'),
   noticeboard: require('../Assets/Icons/noticeboard.png'),
   fees: require('../Assets/Icons/fees.png'),
   leave: require('../Assets/Icons/leave.png'),
   visitorbook: require('../Assets/Icons/visitorbook.png'),
   transport: require('../Assets/Icons/transport.png'),
   room: require('../Assets/Icons/room.png'),
   todolist: require('../Assets/Icons/to-do-list.png'),
   library: require('../Assets/Icons/library.png'),
   routine: require('../Assets/Icons/routine.png'),
   calendar: require('../Assets/Icons/calendar.png'),
   publishdate: require('../Assets/Icons/publishdate.png'),
   NoDataFound: require('../Assets/Icons/NoDataFound.png'),

   uploadfile: require('../Assets/Icons/uploadfile.png'),
   pdf: require('../Assets/Icons/pdf.png'),
   close: require('../Assets/Icons/close.png'),
   darkMode: require('../Assets/Icons/darkMode.png'),
   camera: require('../Assets/Icons/camera.png'),
   choose: require('../Assets/Icons/choose.png'),
   edit: require('../Assets/Icons/edit.png'),
   delete: require('../Assets/Icons/delete.png'),
   add: require('../Assets/Icons/add.png'),
   directDownload: require('../Assets/Icons/direct-download.png'),
   leftArrow: require('../Assets/Icons/left-arrow.png'),
   distance: require('../Assets/Icons/distance.png'),
   clock: require('../Assets/Icons/clock.png'),

}